// Passos "Como usar" de cada ferramenta, exibidos na página de Ajuda (/ajuda).
// Texto simples (sem HTML). O catálogo em si vem de tools.ts.
export const HELP_STEPS: Record<string, string[]> = {
  "juntar-pdf": ["Envie dois ou mais PDFs.", "Arraste os arquivos para definir a ordem (ou use as setas ↑ ↓).", "Clique em Juntar PDF."],
  "dividir-pdf": ["Envie o PDF.", "Escolha Intervalo (ex.: 1-3) ou Cada página.", "Clique em Dividir PDF."],
  "rodar-pdf": ["Envie um ou mais PDFs.", "Escolha o sentido do giro (90° / 180°).", "Clique em Rodar PDF."],
  "organizar-pdf": ["Envie o PDF.", "Arraste as miniaturas para reordenar (ou use ← →); remova com ✕.", "Clique em Organizar PDF."],
  "digitalizar-pdf": ["Envie as fotos/imagens dos documentos.", "Ajuste a ordem das páginas.", "Clique em Gerar PDF."],
  "extrair-paginas": ["Envie o PDF.", "Digite as páginas a manter (ex.: 1-3, 5).", "Clique em Extrair páginas."],
  "remover-paginas": ["Envie o PDF.", "Digite as páginas a remover (ex.: 2, 6-7).", "Clique em Remover páginas."],
  "dividir-por-tamanho": ["Envie o PDF grande.", "Defina o tamanho máximo de cada parte (MB).", "Clique em Dividir por tamanho — sai um .zip com as partes."],
  "padronizar-tamanho": ["Envie o PDF.", "Escolha A4 ou Carta.", "Clique em Padronizar tamanho."],
  "comprimir-pdf": ["Envie o PDF.", "Escolha o nível de compressão.", "Clique em Comprimir e veja a prévia “Original → Comprimido (% menor)”.", "Clique em Baixar PDF comprimido."],
  "reparar-pdf": ["Envie o PDF danificado.", "Clique em Reparar e baixe o arquivo recuperado."],
  "tons-de-cinza": ["Envie o PDF colorido.", "Clique em Converter para tons de cinza."],
  "pdf-para-word": ["Envie o PDF.", "Clique em Converter para Word (.docx)."],
  "pdf-para-powerpoint": ["Envie o PDF.", "Clique em Converter para PowerPoint (.pptx)."],
  "pdf-para-excel": ["Envie um PDF com tabela.", "Clique em Converter para Excel (.xlsx)."],
  "word-para-pdf": ["Envie o arquivo Word.", "Clique em Converter para PDF."],
  "powerpoint-para-pdf": ["Envie o arquivo PowerPoint.", "Clique em Converter para PDF."],
  "excel-para-pdf": ["Envie a planilha Excel.", "Clique em Converter para PDF."],
  "pdf-para-jpg": ["Envie o PDF.", "Escolha a qualidade.", "Clique em Converter para JPG (uma imagem por página)."],
  "jpg-para-pdf": ["Envie uma ou mais imagens JPG/PNG.", "Ajuste a ordem.", "Clique em Converter para PDF."],
  "html-para-pdf": ["Cole uma URL ou o HTML.", "Clique em Gerar PDF."],
  "pdf-para-html": ["Envie o PDF.", "Clique em Converter para HTML — sai um arquivo .html fiel ao original, com texto selecionável."],
  "pdf-para-pdfa": ["Envie o PDF.", "Clique em Converter para PDF/A (arquivamento de longo prazo)."],
  "pdf-para-csv": ["Envie um PDF com tabela.", "Clique em Converter para CSV."],
  "extrair-texto": ["Envie o PDF.", "Clique em Extrair texto (.txt)."],
  "extrair-imagens": ["Envie o PDF.", "Clique em Extrair imagens — sai um .zip."],
  "pdf-para-png": ["Envie o PDF.", "Escolha a qualidade.", "Clique em Converter para PNG."],
  "editar-pdf": ["Envie o PDF.", "Adicione texto, imagens ou formas na página.", "Clique em Baixar PDF editado."],
  "marca-dagua": ["Envie o PDF.", "Escreva o texto (ou escolha imagem) e ajuste posição e transparência.", "Clique em Adicionar marca d'água."],
  "numeros-de-pagina": ["Envie o PDF.", "Escolha a posição e o formato.", "Clique em Adicionar números."],
  "comparar-pdf": ["Envie os dois PDFs (antes e depois).", "Veja o realce visual das diferenças lado a lado.", "Clique em Comparar texto para ver o que foi removido (vermelho) e adicionado (verde)."],
  "recortar-pdf": ["Envie o PDF.", "Ajuste as margens — a área escura será removida (prévia ao vivo).", "Clique em Recortar e baixar PDF."],
  "formularios-pdf": ["Envie um PDF com formulário.", "Preencha os campos detectados.", "Clique em Preencher e baixar."],
  "achatar-pdf": ["Envie o PDF com formulário preenchido.", "Clique em Achatar e baixar — os campos ficam fixos."],
  "editar-metadados": ["Envie o PDF.", "Edite título, autor, assunto e palavras-chave.", "Clique em Salvar metadados."],
  "assinar-pdf": ["Envie o PDF.", "Crie sua assinatura (desenhar, digitar ou imagem).", "Clique no documento para posicionar e ajuste o tamanho.", "Clique em Assinar e baixar PDF."],
  "assinar-certificado": ["Envie o PDF.", "Envie o certificado A1 (.pfx/.p12) e digite a senha.", "Opcional: motivo, local e onde mostrar o carimbo.", "Clique em Assinar com certificado — assinatura PAdES/ICP-Brasil."],
  "proteger-pdf": ["Envie o PDF.", "Defina uma senha.", "Clique em Proteger — o PDF passa a exigir senha para abrir."],
  "desbloquear-pdf": ["Envie o PDF protegido.", "Digite a senha.", "Clique em Desbloquear."],
  "ocultar-pdf": ["Envie o PDF.", "Desenhe tarjas sobre o que quer esconder.", "Clique em Ocultar e baixar."],
  "ocr-pdf": ["Envie um PDF escaneado (imagem).", "Escolha o idioma.", "Clique em Aplicar OCR — o texto fica pesquisável."],
  "imagem-para-texto": ["Envie uma imagem (JPG/PNG) com texto.", "Escolha o idioma.", "Clique em Ler texto da imagem (.txt)."],
};
